//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeHouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заказы()
        {
            this.Платежи = new HashSet<Платежи>();
            this.ПозицииЗаказа = new HashSet<ПозицииЗаказа>();
        }
    
        public int IDЗаказа { get; set; }
        public string ТипЗаказа { get; set; }
        public string Статус { get; set; }
        public string Номер_заказа { get; set; }
        public System.DateTime ВремяСоздания { get; set; }
        public Nullable<System.DateTime> ВремяЗавершения { get; set; }
        public Nullable<decimal> ИтоговаяСумма { get; set; }
        public string СпособОплаты { get; set; }
        public string КомментарийКлиента { get; set; }
        public Nullable<int> IDСотрудника { get; set; }
    
        public virtual Сотрудники Сотрудники { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Платежи> Платежи { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ПозицииЗаказа> ПозицииЗаказа { get; set; }
    }
}
