//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeHouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ингредиенты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ингредиенты()
        {
            this.СоставБлюда = new HashSet<СоставБлюда>();
        }
    
        public int IDИнгредиента { get; set; }
        public string Наименование { get; set; }
        public string ЕдиницаИзмерения { get; set; }
        public string ТекущийОстаток { get; set; }
        public string МинимальныйЗапас { get; set; }
        public string СебестоимостьЗаЕдиницу { get; set; }
        public string Поставщик { get; set; }
        public string СрокГодности { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СоставБлюда> СоставБлюда { get; set; }
    }
}
