//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeHouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Отчеты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Отчеты()
        {
            this.ОтчетПерсонала = new HashSet<ОтчетПерсонала>();
        }
    
        public int IDОтчета { get; set; }
        public string ТипОтчета { get; set; }
        public string НачалоПериода { get; set; }
        public string КонецПериода { get; set; }
        public System.DateTime ВремяФормирования { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ОтчетПерсонала> ОтчетПерсонала { get; set; }
    }
}
