//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeHouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class ПозицииЗаказа
    {
        public int IDПозиции { get; set; }
        public int IDЗаказа { get; set; }
        public int IDТовара { get; set; }
        public string Количество { get; set; }
        public string Модификация { get; set; }
        public decimal ЦенаНаМомент { get; set; }
    
        public virtual Заказы Заказы { get; set; }
        public virtual Меню Меню { get; set; }
    }
}
