//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeHouseLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ОтчетПерсонала
    {
        public int IDОтчета { get; set; }
        public int IDСотрудника { get; set; }
        public string Показатели { get; set; }
    
        public virtual Отчеты Отчеты { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
    }
}
