//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeHouseLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Платежи
    {
        public int IDПлатежа { get; set; }
        public int IDЗаказа { get; set; }
        public decimal Сумма { get; set; }
        public string СтатусПлатежа { get; set; }
    
        public virtual Заказы Заказы { get; set; }
    }
}
