//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeHouseLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class СоставБлюда
    {
        public int IDТовара { get; set; }
        public int IDИнгредиента { get; set; }
        public string Количество { get; set; }
    
        public virtual Ингредиенты Ингредиенты { get; set; }
        public virtual Меню Меню { get; set; }
    }
}
