//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPICoffee.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CoffeeHouseEntities : DbContext
    {
        public CoffeeHouseEntities()
            : base("name=CoffeeHouseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Заказы> Заказы { get; set; }
        public virtual DbSet<Ингредиенты> Ингредиенты { get; set; }
        public virtual DbSet<Меню> Меню { get; set; }
        public virtual DbSet<ОтчетПерсонала> ОтчетПерсонала { get; set; }
        public virtual DbSet<Отчеты> Отчеты { get; set; }
        public virtual DbSet<Платежи> Платежи { get; set; }
        public virtual DbSet<ПозицииЗаказа> ПозицииЗаказа { get; set; }
        public virtual DbSet<Роль> Роль { get; set; }
        public virtual DbSet<СоставБлюда> СоставБлюда { get; set; }
        public virtual DbSet<Сотрудники> Сотрудники { get; set; }
    }
}
